[package]
name = "lpsolver3"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = { version = "0.3.76", features = ["HtmlSelectElement"] }
nalgebra = "0.33.2"
wasm-bindgen = "0.2.99"
wasm-logger = "0.2.0"
yew = { version = "0.21", features = ["csr"] }
log = "0.4.22"
